image: cmake:latest

stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build
    - make
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days  
    paths:
      - "build/emulator"
