image: gitpod/workspace-full-vnc
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
    
tasks:
  - init: make


# example .gitpod.yml from https://github.com/gitpod-io/demo-multi-repo-frontend
additionalRepositories:
  - url: https://gitlab.com/dulatello08/cpu-assembler
    # checkoutLocation is relative to /workspaces
    checkoutLocation: cpu-assembler

vscode:
  extensions:
    - Equinusocio.vsc-community-material-theme